# Text File Handling 

#### Read the .txt file and display its content when file is in same folder in read mode

#### File Handling methods

1) readlines() - Displays all the content of the file(from the cursor position) in a list<br>

2) read() - Read at most n characters from stream or file.

3) seek() - Repositions the cursor to a particular index.

4) tell() - Returns current cursor position.

5) close() - File is closed to deallocate(remove) the memory.

6) write() - Used to write new content(data) to the file

In [1]:
# mode = 'r' => read mode
f = open('demo1.txt','r')
r1 = f.readlines()  # returns a list
print(r1)
f.close()  # to deallocate the memory

['Hi,\n', 'This file is for testing purpose only.\n', 'And this file is prepared by none other than Chirag Kaura']


#### Read the .txt file and display its content when file is at a differnt path

In [2]:
print('Hello \\world')

Hello \world


In [3]:
f1 = open('C:\\Users\\world\\OneDrive\\Documents\\SmartKnower\\trial.txt','r')
r1 = f1.readlines()
print(r1)
f1.close()

['This is another text file for testing with the another location.\n', 'We are going to perform differnt test like:\n', '1. opening \n', '2. writing \n', '3. seeking \n', '4. reading and closing the file']


In [4]:
f1 = open('C:/Users/world/OneDrive/Documents/SmartKnower/trial.txt','r')
r1 = f1.readlines()
print(r1)
f1.close()

['This is another text file for testing with the another location.\n', 'We are going to perform differnt test like:\n', '1. opening \n', '2. writing \n', '3. seeking \n', '4. reading and closing the file']


In [5]:
f = open('demo1.txt','r')
r1 = f.read(21)
print(r1)
print(f.tell())

Hi,
This file is for 
22


In [6]:
r2 = f.read(12)
print(r2)
print(f.tell())
# 12th character is \n

testing purp
34


In [7]:
# tell() - returns the current cursor position
print(f.tell())

34


In [8]:
# seek() - it repositions the cursor to a particular index
f.seek(5)
r3 = f.read(7)
print(r3)
print(f.tell())

This fi
12


In [9]:
# seek() - it repositions the cursor to a particular index
f.seek(-1)
r3 = f.read(7)
print(r3)
print(f.tell())

ValueError: negative seek position -1

In [10]:
# tell() - returns current cursor position
print(f.tell())

12


In [11]:
# close the file - to deallocate the memory
f.close()

In [12]:
d = open('demo2.txt','r')
res = d.readlines()
print(res)
d.close()

['Data Science and ML']


#### Reading the file in append mode

append mode is used to add some content(new data) to the file.

In [13]:
w = open('demo1.txt',mode='r')
w.write('\nJune Ends soon')
w.write('\nPython is fun to learn')
w.close()

UnsupportedOperation: not writable

In [14]:
# 'a' implies append mode
w = open('demo2.txt',mode='a')
w.write('\nJune Ends soon')
w.write('\nPython is fun to learn')
w.write('\nI am a good man')
w.close()

In [15]:
f = open('demo2.txt','r')
print(f.readlines())

['Data Science and ML\n', 'June Ends soon\n', 'Python is fun to learn\n', 'I am a good man']


#### Reading File in write mode
It is meant to create a new file and add content to the file

In [16]:
# w  implies write mode
g = open('demo3.txt','w') # creating a new file - demo3.txt
g.write('New file created')
g.write('\nMultiverse of Madness has been released')
g.close()

In [17]:
f = open('demo3.txt','r')
print(f.readlines())

['New file created\n', 'Multiverse of Madness has been released']


#### Opening a pre-exitsing file in write mode => overwrites the content if write function is used.

In [18]:
s = open('demo2.txt','w') # opening a pre-existing file in 'w' mode
s.write('Data Science and ML')
s.close()

In [19]:
f = open('demo2.txt','r')
print(f.readlines())

['Data Science and ML']


# Numpy Module

In [20]:
import numpy as np
# np is the alias name for numpy library

#### Array in numpy

1) Array is an ordered collection of homogeneous elements in numpy.<br>
2) All the elements in the numpy array must be of same data type<br>

In [21]:
q = [12,13,14,16,23,24]
print(q)
print(type(q))

[12, 13, 14, 16, 23, 24]
<class 'list'>


In [22]:
n1 = np.array(q)
print(n1)
print(type(n1))

[12 13 14 16 23 24]
<class 'numpy.ndarray'>


In [23]:
w1 = [10,20,30,4.5,7.3,2.8]
print(w1)
print(type(w1))
print(type(w1[0]),type(w1[-1]))

[10, 20, 30, 4.5, 7.3, 2.8]
<class 'list'>
<class 'int'> <class 'float'>


In [24]:
n2 = np.array(w1)
print(n2)
print(type(n2))
print(type(n2[0]),type(n2[-1]))

[10.  20.  30.   4.5  7.3  2.8]
<class 'numpy.ndarray'>
<class 'numpy.float64'> <class 'numpy.float64'>


In [25]:
w1 = [10,20,'30',4.5,7.3,2.8]
print(w1)
print(type(w1))
n2 = np.array(w1)
print(n2)
print(type(n2))
print(type(n2[2]))

[10, 20, '30', 4.5, 7.3, 2.8]
<class 'list'>
['10' '20' '30' '4.5' '7.3' '2.8']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [26]:
q1 = ['India','Japan',10,20,5.7,8.3]
n3 = np.array(q1)
print(n3)
print(type(n3[-1]))

['India' 'Japan' '10' '20' '5.7' '8.3']
<class 'numpy.str_'>


#### Custom numpy array
1) np.zeros() - used to create an array of zeros of specified shape<br>
1) np.ones() - used to create an array of ones of specified shape

In [27]:
a1 = np.zeros((4,3)) # default data type is float
print(a1)
print(a1.shape) 
print(a1.dtype)
# shape - returns the number of rows and columns (dimensions of the numpy array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(4, 3)
float64


In [28]:
a1 = np.ones((3,5),dtype='int') # changed the data type to int
print(a1)
print(a1.shape)  # rows and columns
print(a1.dtype)  # data type of np.array
print(a1.ndim)   # the dimension
print(a1.size)   # number of elmenets in the arary

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
(3, 5)
int32
2
15


In [29]:
a1 = np.ones((2,3,5),dtype=int) # changed the data type to int
print(a1)
print(a1.shape)  # rows and columns
print(a1.dtype)  # data type of np.array
print(a1.ndim)   # the dimension
print(a1.size)   # number of elmenets in the arary

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
(2, 3, 5)
int32
3
30


In [30]:
a3 = np.ones((7),dtype=int) #1 dimension only in x axis
print(a3)
print(a3.shape)
print(a3.size)
print(a3.ndim)

[1 1 1 1 1 1 1]
(7,)
7
1


#### Note
A numpy array can be reshaped into product of its factors of its length(number of elements in the array)

In [31]:
v1 = np.array([2,4,6,8,10,12,14,16,18,20,22,24])
print(v1)
print(len(v1))
print(v1.shape)
# factors of 12 - 1,2,3,4,6,12,
# Pairs are - (1,12),(12,1),(2,6),(6,2),(3,4),(4,3)

[ 2  4  6  8 10 12 14 16 18 20 22 24]
12
(12,)


In [32]:
v1 = np.array([2,4,6,8,10,12,14,16,18,20,22,24]).reshape(6,2)
print(v1)
print(v1.shape)

[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]
 [22 24]]
(6, 2)


### np.arange(start,end,step)

In [33]:
for i in range(5,12): # start=5,end=12,step=1
    print(i,end=" ")

5 6 7 8 9 10 11 

In [34]:
d1 = np.arange(5,12) # start= 5, end=12, step=1
print(d1)
print(type(d1))

[ 5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [35]:
d2 = np.arange(14,56,5) # start=14, end=56, step=5
print(d2)

[14 19 24 29 34 39 44 49 54]


In [36]:
d2 = np.arange(30,5,-4) # start=30, end=5, step=-4
print(d2)
print(len(d2))

[30 26 22 18 14 10  6]
7


In [37]:
d3 = np.arange(8,75,6).reshape(3,4)
print(d3)
print(d3.shape)

[[ 8 14 20 26]
 [32 38 44 50]
 [56 62 68 74]]
(3, 4)


In [38]:
d1 = np.arange(10,22).reshape(4,3)
print(d1)
print(d1.shape)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
(4, 3)


In [39]:
d1.reshape(6,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [40]:
print(d1.shape) # dont effect the original shape

(4, 3)


In [41]:
# shape
d1.shape = (2,6)
print(d1)

[[10 11 12 13 14 15]
 [16 17 18 19 20 21]]


In [42]:
print(d1.shape)

(2, 6)


In [43]:
s1 = np.arange(10,28).reshape(2,3,3)
print(s1)
print(s1.shape)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
(2, 3, 3)


In [44]:
s1.shape = (6,3)
print(s1)
print(s1.shape)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]
(6, 3)


#### Attributes of a numpy Array
1) dtype - Returns the data type of the array<br>
2) ndim - Returns the number of dimensions<br>
3) shape - Returns the number of rows and columns (starting from 2D and onwards)<br>
4) size - It returns the total number of elements<br>

In [45]:
g1 = np.arange(1,10).reshape(3,3)
print(g1)
print(g1.dtype) # int
print(g1.ndim)  # 2
print(g1.shape) # (rows,columns)
print(g1.size)  # 9

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int32
2
(3, 3)
9


In [46]:
np.arange(0.5,3.5)

array([0.5, 1.5, 2.5])

In [47]:
g2 = np.arange(1,19).reshape(3,6)
print(g2)
print(g2.dtype)
print(g2.ndim)
print(g2.shape)
print(g2.size)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
int32
2
(3, 6)
18


#### np.linspace()
Generates linearly spaced elements over a specified range.

In [48]:
a = np.linspace(2,10,3) # start=2, end=10, no. of elements=3
print(a)
# linearly spaced means difference between 6 and 2 and between 10 and 6 is same

[ 2.  6. 10.]


In [49]:
a1 = np.linspace(2,10,5)
print(a1)

[ 2.  4.  6.  8. 10.]


In [50]:
a2 = np.linspace(7,18,8)
print(a2)

[ 7.          8.57142857 10.14285714 11.71428571 13.28571429 14.85714286
 16.42857143 18.        ]


In [51]:
a3 = np.linspace(5,30) #default value of linespace is 50
print(len(a3))
print(a3)

50
[ 5.          5.51020408  6.02040816  6.53061224  7.04081633  7.55102041
  8.06122449  8.57142857  9.08163265  9.59183673 10.10204082 10.6122449
 11.12244898 11.63265306 12.14285714 12.65306122 13.16326531 13.67346939
 14.18367347 14.69387755 15.20408163 15.71428571 16.2244898  16.73469388
 17.24489796 17.75510204 18.26530612 18.7755102  19.28571429 19.79591837
 20.30612245 20.81632653 21.32653061 21.83673469 22.34693878 22.85714286
 23.36734694 23.87755102 24.3877551  24.89795918 25.40816327 25.91836735
 26.42857143 26.93877551 27.44897959 27.95918367 28.46938776 28.97959184
 29.48979592 30.        ]


In [52]:
a3 = np.linspace(5,30,retstep=True)
print(len(a3))
print(a3)

2
(array([ 5.        ,  5.51020408,  6.02040816,  6.53061224,  7.04081633,
        7.55102041,  8.06122449,  8.57142857,  9.08163265,  9.59183673,
       10.10204082, 10.6122449 , 11.12244898, 11.63265306, 12.14285714,
       12.65306122, 13.16326531, 13.67346939, 14.18367347, 14.69387755,
       15.20408163, 15.71428571, 16.2244898 , 16.73469388, 17.24489796,
       17.75510204, 18.26530612, 18.7755102 , 19.28571429, 19.79591837,
       20.30612245, 20.81632653, 21.32653061, 21.83673469, 22.34693878,
       22.85714286, 23.36734694, 23.87755102, 24.3877551 , 24.89795918,
       25.40816327, 25.91836735, 26.42857143, 26.93877551, 27.44897959,
       27.95918367, 28.46938776, 28.97959184, 29.48979592, 30.        ]), 0.5102040816326531)


In [53]:
a4 = np.linspace(2,15,10)
print(a4)

[ 2.          3.44444444  4.88888889  6.33333333  7.77777778  9.22222222
 10.66666667 12.11111111 13.55555556 15.        ]


In [54]:
a5 = np.linspace(2,15,10,dtype=int)  # uses floor
print(a5)

[ 2  3  4  6  7  9 10 12 13 15]


### np.dot() 
Computes the Dot product of the arrays.

In [55]:
a1 = np.arange(1,7).reshape(2,3)
print(a1)
print(a1.shape)
a2 = np.arange(-10,5).reshape(3,5)
print(a2)
print(a2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[-10  -9  -8  -7  -6]
 [ -5  -4  -3  -2  -1]
 [  0   1   2   3   4]]
(3, 5)


In [56]:
res = np.dot(a1,a2)
print(res)
print(res.shape)

[[-20 -14  -8  -2   4]
 [-65 -50 -35 -20  -5]]
(2, 5)


In [57]:
t1 = np.arange(1,7).reshape(2,3)
print(t1)
print(t1.shape)
t2 = np.arange(-10,5).reshape(5,3)
print(t2)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[-10  -9  -8]
 [ -7  -6  -5]
 [ -4  -3  -2]
 [ -1   0   1]
 [  2   3   4]]


In [58]:
res1 = np.dot(t1,t2.T) #.T makes the transpose of the matrix
print(res1)

[[ -52  -34  -16    2   20]
 [-133  -88  -43    2   47]]
