### 1) Univariate Data Analysis
#### a) Mean, Median, Mode<br>

#### b) Variance<br> 
sum(xi-xmean)^2/N, population var<br>
sum(xi-xmean)^2/(N-1), Sample var<br>

#### c) Std_Deviation<br>
sqrt(sum(xi-xmean)^2/N), population std_dev<br>
sqrt(sum(xi-xmean)^2/(N-1)), Sample std_dev<br>

#### d) Range = max - min<br>

### 2) Bivaraite/Multivariate Data Analysis<br>
#### a) Covariance<br>
#### b) Correlation<br>

In [1]:
import statistics as st

### Univariate Data Analysis

In [2]:
s1=[12,10,7,5,18,6,10,13,19,7]
print(s1)
print('Mean',st.mean(s1))
print('Median',st.median(s1))
print('Mode',st.mode(s1))

[12, 10, 7, 5, 18, 6, 10, 13, 19, 7]
Mean 10.7
Median 10.0
Mode 10


In [3]:
print('Var',st.variance(s1))
print('Std',st.stdev(s1))

Var 23.566666666666666
Std 4.8545511292669135


### Bi-variate Data Analysis

#### Covariance

1) It helps us understand the relationship between two variables<br>

2) Its range is between -infinity to + inifinity<br>

3) Covariance values are not standardized<br>

4) If cov(x,y)> 0 => Positive Realtionship<br>
    If cov(x,y)< 0 => Negative Realtionship<br>

5) Positive covariance =><br>
    If x is increasing, y also increases<br>
    If x is decreasing, y also deccreases<br>

6) Negative covariance =><br>
    If x is increasing, y decreases<br>
    If x is decreasing, y increases<br>
    
7) Formula<br>
pop cov       cov(x,y) = sum((x-xmean) * (y-ymean))/N<br>
samp cov      cov(x,y) = sum((x-xmean) * (y-ymean))/(N-1)<br>

8) cov(x,y) = cov(y,x)<br>
    cov(x,x) = var(x)<br>
    cov(y,y) = var(y)<br>

#### Correlation<br>

1) It is the standardized version of Covariance.<br>

2) It gives the strength and magnitude of relationship between 2 or more variables<br>

3) It ranges from -1 to +1 where -1 indicates strong negative correlation and +1 indicates strong positive correaltion.<br>

4) cov(x,y) = sum((x-xmean) * (y-ymean))/N, pop cov<br>

5) corr(x,y) = sum((x-xmean) * (y-ymean)) / sqrt(sum((x-xmean)^2 * sum((y-ymean)^2))<br>

6) If corr(x,y)> 0 => Positive Realtionship<br>
    If corr(x,y)< 0 => Negative Realtionship<br>

7) Positive correlation =><br>
    If x is increasing, y also increases<br>
    If x is decreasing, y also deccreases<br>

8) Negative correlation =><br>
    If x is increasing, y decreases<br>
    If x is decreasing, y increases<br>

9) corr(x,y) = corr(y,x)<br>
    corr(x,x) = corr(y,y) = 1<br>

In [4]:
x = [2,5,7,8,12,17,21]
y = [3,4,10,11,20,21,24]

In [5]:
import numpy as np
print('Cov\n',np.cov(x,y))
# [cov(x,x),cov(x,y)]
# [cov(y,x),cov(y,y)]

# cov(x,y) = cov(y,x)
# cov(x,x) = var(x)
# cov(y,y) = var(y)

Cov
 [[45.9047619  54.73809524]
 [54.73809524 71.23809524]]


In [6]:
print('Corr\n',np.corrcoef(x,y))
# [corr(x,x),corr(x,y)]
# [corr(y,x),corr(y,y)]
#
# corr(x,x) = corr(y,y) = 1
# corr(x,y) = corr(y,x)

Corr
 [[1.         0.95720435]
 [0.95720435 1.        ]]


#### Implement Covariane, correleation, varaince and Std deviation using a custom python function

In [7]:
r = [15,18,24,19,18,10,14,17]

def var_std(w):
    meanw = sum(w)/len(w)
    temp = 0
    for i in range(len(w)):
        temp += (w[i] - meanw)**2
    var_pop = temp/len(w)
    var_samp = temp/(len(w)-1)
    std_pop = np.sqrt(var_pop)
    std_samp = np.sqrt(var_samp)
    print('Var_pop',var_pop)
    print('Var_samp',var_samp)
    print('Std_pop',std_pop)
    print('Std_samp',std_samp)
    
var_std(r)

Var_pop 14.609375
Var_samp 16.696428571428573
Std_pop 3.822221212855164
Std_samp 4.086126352846737


In [8]:
print('Var_Samp',st.variance(r))
print('Std_samp',st.stdev(r))

Var_Samp 16.696428571428573
Std_samp 4.086126352846737


#### Custom Covariance

In [9]:
x = [2,5,7,8,12,17,21]
y = [3,4,10,11,20,21,24]

def covar(x,y):
    mx,my = sum(x)/len(x), sum(y)/len(y)
    temp = 0
    for i in range(len(x)):
        temp += (x[i] - mx)*(y[i] - my)
    cov_pop = temp/len(x)
    cov_samp = temp/(len(x)-1)
    print('Cov_pop',cov_pop)
    print('Cov_samp',cov_samp)

    
covar(x,y)
var_std(x)
var_std(y)

Cov_pop 46.91836734693878
Cov_samp 54.73809523809524
Var_pop 39.3469387755102
Var_samp 45.904761904761905
Std_pop 6.272713828600042
Std_samp 6.77530529974568
Var_pop 61.06122448979592
Var_samp 71.23809523809524
Std_pop 7.814168189244196
Std_samp 8.440266301373153


In [10]:
print('Sample Covariance')
print(np.cov(x,y))

Sample Covariance
[[45.9047619  54.73809524]
 [54.73809524 71.23809524]]


In [11]:
# cov(x,y) = sum((x-xmean) * (y-ymean))/N, pop cov
# corr(x,y) = sum((x-xmean) * (y-ymean)) / sqrt(sum((x-xmean)^2 * sum((y-ymean)^2))

In [12]:
x = [2,5,7,8,12,17,21]
y = [3,4,10,11,20,21,24]

def correlation(x,y):
    mx,my = sum(x)/len(x), sum(y)/len(y)
    temp = 0
    for i in range(len(x)):
        temp += (x[i] - mx)*(y[i] - my)
    xs = [(i-mx)**2 for i in x]
    ys = [(i-my)**2 for i in y]
    deno = np.sqrt(sum(xs)*sum(ys))
    corr = temp/deno
    print('Correlation',corr)
    
correlation(x,x)
correlation(x,y)
correlation(y,x)
correlation(y,y)

Correlation 1.0
Correlation 0.9572043462517711
Correlation 0.9572043462517711
Correlation 1.0


In [13]:
print('Corr')
print(np.corrcoef(x,y))

Corr
[[1.         0.95720435]
 [0.95720435 1.        ]]
